-- MySQL Script generated by MySQL Workbench
-- 02/23/15 09:41:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `academia` ;

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `academia` ;

-- -----------------------------------------------------
-- Table `alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `alumno` (
  `idalumno` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(25) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechanacimiento` DATE NULL,
  `sexo` CHAR NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(15) NULL,
  `titularnombres` VARCHAR(45) NULL,
  `titularapellidos` VARCHAR(45) NULL,
  `estado` TINYINT(1) NOT NULL,
  `titulardpi` VARCHAR(15) NULL,
  `establecimiento` VARCHAR(100) NULL,
  `direccionestablecimiento` VARCHAR(125) NULL,
  `gradoestablecimiento` VARCHAR(45) NULL,
  `codigomineduc` VARCHAR(50) NULL,
  `fechabaja` DATE NULL,
  `observacion` VARCHAR(250) NULL,
  PRIMARY KEY (`idalumno`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_UNIQUE` ON `alumno` (`codigo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipopago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipopago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipopago` (
  `idtipopago` INT NOT NULL AUTO_INCREMENT,
  `tipopago` VARCHAR(20) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fecharegistro` DATE NOT NULL,
  PRIMARY KEY (`idtipopago`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `tipopago_UNIQUE` ON `tipopago` (`tipopago` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombrecurso` VARCHAR(100) NOT NULL,
  `fecharegistro` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombrecurso_UNIQUE` ON `curso` (`nombrecurso` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profesor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `profesor` (
  `idcatedratico` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(16) NULL,
  `fechainicio` DATE NOT NULL,
  PRIMARY KEY (`idcatedratico`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_UNIQUE` ON `profesor` (`codigo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `otrospagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otrospagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `otrospagos` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idpago`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fechacreacion` DATE NULL,
  `fechabaja` DATE NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `usuario_UNIQUE` ON `usuario` (`usuario` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `recibodepago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recibodepago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `recibodepago` (
  `idrecibo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `alumno_idalumno` INT NOT NULL,
  `tipopago_idtipopago` INT NOT NULL,
  `total` FLOAT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idrecibo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `descripcionrecibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `descripcionrecibo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `descripcionrecibo` (
  `iddescripcionrecibo` INT NOT NULL AUTO_INCREMENT,
  `cantidad` FLOAT NULL,
  `precio` FLOAT NOT NULL,
  `recibo_idrecibo` INT NOT NULL,
  `pago_idpago` INT NOT NULL,
  PRIMARY KEY (`iddescripcionrecibo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cicloescolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cicloescolar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cicloescolar` (
  `idañoescolar` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NOT NULL,
  `fechainicio` DATE NULL,
  `fechacierre` DATE NULL,
  PRIMARY KEY (`idañoescolar`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `faltaalumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faltaalumno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `faltaalumno` (
  `idfaltaalumno` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `alumno_idalumno` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idfaltaalumno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `observacion` VARCHAR(150) NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `descripcion_UNIQUE` ON `carrera` (`descripcion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `fechainicio` DATE NOT NULL,
  `fechafin` DATE NOT NULL,
  `cantalumnos` INT NOT NULL,
  `dia` VARCHAR(20) NOT NULL,
  `horariode` TIME NOT NULL,
  `horarioa` TIME NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `carrera_idcarrera` INT NOT NULL,
  `profesor_idcatedratico` INT NOT NULL,
  `inscripcion` FLOAT NOT NULL,
  `colegiatura` FLOAT NOT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `alumnosengrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumnosengrupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `alumnosengrupo` (
  `iddetallegrupo` INT NOT NULL AUTO_INCREMENT,
  `alumno_idalumno` INT NOT NULL,
  `grupo_idgrupo` INT NOT NULL,
  `fechainicio` DATE NOT NULL,
  `beca` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`iddetallegrupo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `notas` (
  `idnotas` INT NOT NULL AUTO_INCREMENT,
  `notafinal` FLOAT NULL,
  `curso_idcurso` INT NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  PRIMARY KEY (`idnotas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pensum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pensum` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pensum` (
  `idpensum` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `carrera_idcarrera` INT NOT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idpensum`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `descripcion_UNIQUE` ON `pensum` (`descripcion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detallepensun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detallepensun` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detallepensun` (
  `iddetallepensun` INT NOT NULL AUTO_INCREMENT,
  `pensun_idpensun` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`iddetallepensun`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mes` (
  `idmes` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idmes`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `mes_UNIQUE` ON `mes` (`mes` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyeccionpagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyeccionpagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyeccionpagos` (
  `idproyeccionpagos` INT NOT NULL AUTO_INCREMENT,
  `mes_idmes` INT NOT NULL,
  `año` INT NULL,
  `monto` FLOAT NOT NULL,
  `fechavencimiento` DATE NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 0,
  `asignado` TINYINT(1) NULL DEFAULT 1,
  `alumnosengrupo_iddetallegrupo` INT NOT NULL,
  PRIMARY KEY (`idproyeccionpagos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detrecibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detrecibo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detrecibo` (
  `iddetrecibo` INT NOT NULL AUTO_INCREMENT,
  `recibodepago_idrecibo` INT NOT NULL,
  `proyeccionpagos_idproyeccionpagos` INT NOT NULL,
  PRIMARY KEY (`iddetrecibo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mora` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mora` (
  `idmora` INT NOT NULL AUTO_INCREMENT,
  `mora` FLOAT NULL,
  `exoneracion` FLOAT NULL DEFAULT 0,
  `estado` TINYINT(1) NULL DEFAULT 0,
  `proyeccionpagos_idproyeccionpagos` INT NOT NULL,
  PRIMARY KEY (`idmora`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pagos` (
  `idpagos` INT NOT NULL AUTO_INCREMENT,
  `mes_idmes` INT NOT NULL,
  `año` INT NULL,
  `monto` FLOAT NULL,
  `fechavencimiento` DATE NULL,
  `grupo_idgrupo` INT NOT NULL,
  PRIMARY KEY (`idpagos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `principal` VARCHAR(60) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre_UNIQUE` ON `menu` (`nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfilusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfilusuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `perfilusuario` (
  `idperfilusuario` INT NOT NULL AUTO_INCREMENT,
  `menu_idmenu` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idperfilusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `academia`;
INSERT INTO `usuario` (`idusuario`, `nombre`, `usuario`, `password`, `estado`, `fechacreacion`, `fechabaja`) VALUES (1, 'Administrador', 'admin', 'admin1', true, '2015/02/23', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mes`
-- -----------------------------------------------------
START TRANSACTION;
USE `academia`;
INSERT INTO `mes` (`idmes`, `mes`) VALUES (1, 'Enero');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (2, 'Febrero');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (3, 'Marzo');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (4, 'Abril');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (5, 'Mayo');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (6, 'Junio');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (7, 'Julio');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (8, 'Agosto');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (9, 'Septiembre');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (10, 'Octubre');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (11, 'Noviembre');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (12, 'Diciembre');
INSERT INTO `mes` (`idmes`, `mes`) VALUES (13, 'Inscripci�n');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
